import type { RulesConfig, RulesTuning } from "../engine/types";

export const livretTuning: RulesTuning = {
  drawWinnerFirst: true,
  globalPrisme: true,
  globalInversion: true,
  bluffJokerColor: false,
  winnerCapturesCommons: true,
};

export const defaultRules: RulesConfig = {
  colors: [
    { id: "or", name: "Or", hex: "#e0b84a" },
    { id: "sarcelle", name: "Sarcelle", hex: "#2ec4b6" },
    { id: "bleuNuit", name: "Bleu nuit", hex: "#3d5a80" },
    { id: "vert", name: "Vert", hex: "#3d9b4a" },
    { id: "rouge", name: "Rouge", hex: "#d64545" },
    { id: "orange", name: "Orange", hex: "#f28c28" },
  ],
  minValue: 1,
  maxValue: 13,
  copiesPerNumbered: 1,
  specialCopies: {
    inversion: 3,
    prisme: 3,
    gele: 3,
    ajoute: 3,
    echange: 3,
    bluff: 7,
  },
  specialColor: {
    inversion: "or",
    prisme: "sarcelle",
    gele: "bleuNuit",
    ajoute: "vert",
    echange: "rouge",
    bluff: "orange",
  },
  distribution: [
    { players: 2, handSize: 6, commonsPerTurn: 4 },
    { players: 3, handSize: 5, commonsPerTurn: 4 },
    { players: 4, handSize: 5, commonsPerTurn: 3 },
    { players: 5, handSize: 4, commonsPerTurn: 3 },
    { players: 6, handSize: 4, commonsPerTurn: 3 },
  ],
  comboRank: {
    high: 1,
    pair: 2,
    twoPair: 3,
    three: 4,
    smallStraight: 5,
    echo: 6,
    bigStraight: 7,
    full: 8,
    four: 9,
    flush: 10,
    rainbow: 11,
    royal: 12,
    prismale: 100,
  },
  comboLabels: {
    high: "Carte haute",
    pair: "Paire simple",
    twoPair: "Double paire",
    three: "Brelan",
    smallStraight: "Petite suite",
    echo: "Écho",
    bigStraight: "Grande suite",
    full: "Full",
    four: "Carré",
    flush: "Couleur",
    rainbow: "Arc-en-ciel",
    royal: "Couleur royale",
    prismale: "Prismale",
  },
  specialLabels: {
    inversion: "Inversion",
    prisme: "Prisme",
    gele: "Gèle",
    ajoute: "Ajoute une carte",
    echange: "Échange de jeu",
    bluff: "Bluff",
  },
  numberedTiers: [
    { min: 1, max: 5, points: 1 },
    { min: 6, max: 10, points: 2 },
    { min: 11, max: 13, points: 3 },
  ],
  specialPoints: {
    bluff: 1,
    gele: 2,
    ajoute: 2,
    inversion: 3,
    prisme: 3,
    echange: 3,
  },
  bonusMostTricks: 6,
  bonusBestFinalHand: 3,
  bonusUnbeatenLast3: 5,
  playMin: 1,
  playMax: 3,
  tuning: livretTuning,
  variantLabel: "iter1-livret",
};

export function cloneRules(rules: RulesConfig): RulesConfig {
  return structuredClone(rules);
}
